# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201808-01

    working_directory: ~/doggmentator
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - run:
          name: create a new virtual env for installing dependecies
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies to run unittests
          command: |
            pip install pytest
            pip install nltk
      - run:
          name: testing
          command: |
            pytest . tests/test_backend.py -v